include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - camel_case_types
    - cancel_subscriptions
    - constant_identifier_names
    - empty_catches
    - file_names
    - library_names
    - no_duplicate_case_values
    - non_constant_identifier_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_generic_function_type_aliases
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - slash_for_doc_comments
    - sort_child_properties_last
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_null_in_if_null_operators
    - unnecessary_string_interpolations
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
